main:
    random_seed: 'vsr'
    saved_dir: './models/acdc_sisr/edsr_net/exp3_x2/train'
    
dataset:
    name: 'AcdcSISRDataset'
    kwargs:
        data_dir: '/home/peter850706/acdc_preprocessed/imgs'
        downscale_factor: 2
        transforms:
            - name: 'Normalize'
              kwargs:
                  means: [54.089]
                  stds: [48.084]
            - name: 'ToTensor'
        augments:
            - name: 'RandomHorizontalFlip'
            - name: 'RandomVerticalFlip'
            - name: 'RandomCropPatch'
              kwargs:
                  size: [32, 32]
                  ratio: 2

dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 16
        valid_batch_size: 1
        shuffle: true
        num_workers: 8

net:
    name: 'EDSRNet'
    kwargs:
        in_channels: 1
        out_channels: 1
        num_resblocks: 32
        num_features: 256
        upscale_factor: 2
        res_scale: 0.1

losses:
    - name: 'L1Loss'
      weight: 1.0

metrics:
    - name: 'PSNR'
    - name: 'SSIM'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.0001
        weight_decay: 0

logger:
    name: 'AcdcSISRLogger'
    kwargs:
        dummy_input: [16, 1, 32, 32]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 10
        early_stop: 0

trainer:
    name: 'AcdcSISRTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 1000